# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: source/conf.py
  builder: html
  fail_on_warning: false

# Build documentation in the "docs/" directory with Sphinx
build:
  os: "ubuntu-22.04"
  apt_packages:
    - graphviz
  tools:
    python: "3.11"
    # You can also specify other tool versions:
    # nodejs: "20"
    # rust: "1.70"
    # golang: "1.20"

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf

python:
  install:
    - requirements: requirements.txt
    # Install our python package before building the docs
    - method: pip
      path: .
